- name: Setup Polkadot Full Node
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name:
          - wget
          - curl
        state: present
        update_cache: yes

    - name: Download Polkadot binary
      get_url:
        url: https://github.com/paritytech/polkadot/releases/download/v1.0.0/polkadot
        dest: /usr/local/bin/polkadot
        mode: '0755'

    - name: Start Polkadot node with warp sync
      shell: |
        nohup /usr/local/bin/polkadot --sync warp > /home/ubuntu/polkadot.log 2>&1 &
