- name: Setup Nginx Reverse Proxy for Polkadot
  hosts: all
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Remove default Nginx configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Create Nginx configuration for Polkadot
      copy:
        dest: /etc/nginx/sites-available/polkadot
        content: |
          server {
              listen 80;

              location / {
                  proxy_pass http://localhost:9933;  # Update with your Polkadot RPC port
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }

              location /ws/ {
                  proxy_pass http://localhost:9944;  # WebSocket port
                  proxy_http_version 1.1;
                  proxy_set_header Upgrade $http_upgrade;
                  proxy_set_header Connection 'upgrade';
                  proxy_set_header Host $host;
                  proxy_cache_bypass $http_upgrade;
              }
          }

    - name: Enable Nginx configuration for Polkadot
      file:
        src: /etc/nginx/sites-available/polkadot
        dest: /etc/nginx/sites-enabled/polkadot
        state: link

    - name: Test Nginx configuration
      command: nginx -t

    - name: Reload Nginx to apply changes
      systemd:
        name: nginx
        state: reloaded

    - name: Start and enable Nginx service
      systemd:
        name: nginx
        enabled: yes
        state: started
