- name: Setup Reverse Proxy for Polkadot Node
  hosts: localhost
  become: yes
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Configure Nginx reverse proxy
      copy:
        dest: /etc/nginx/sites-available/polkadot
        content: |
          server {
              listen 80;

              location /rpc {
                  proxy_pass http://localhost:9944/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }

              location /metrics {
                  proxy_pass http://localhost:9615/;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Enable Nginx site configuration
      file:
        src: /etc/nginx/sites-available/polkadot
        dest: /etc/nginx/sites-enabled/polkadot
        state: link

    - name: Test Nginx configuration
      command: nginx -t

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
